### ISSUE TITLE
Magma: Gatekeep updates according to Gnomon

### ISSUE THREAD

**Issue by graft** [mountetna/monoetna#1221]
Currently Magma is relatively permissive about creating identifiers - any post to /update will create a record, so long as the record is valid. In some cases there might be regular expression validations on the record identifier, but these are not obligate, and might not often be filled in.

Gnomon now allows us to define a grammar covering any identifiers in the project data hierarchy.  Gnomon also provides a method for record of entity creation for each identifier. Both of these now afford us a new way to validate record creation in Magma.

Going forward, Magma projects can be configured to cede responsibility for the existence of identifiers to Gnomon (instead of using the previous validation methods). This is a simple validation for Magma to perform, since it is merely looking up the corresponding entry in Gnomon's identifier list and rejecting the record if it isn't found.

The difficult part would seem to be: where should the flag indicating a project should be gnomon-validated be kept?

**Comment by dtm2451** [comment]
Yes!  Hmmm for the difficult part / flag, I see 2 options:

1) An attribute of the project model called 'records_in_gnomon_first' or something similar?  Key is just that the attribute name should be consistent.  If the attribute both exists and is 'true', then do rely on gnomon for pre-knowledge of identifiers. If it doesn't exist (current state for current projects) or is false, then gnomon is ignored / current status quo.  Optional: We could also mark the attribute as 'restricted' if we don't want to add visible clutter to projects' lay viewers.
I think this option works well because:
- Every project has a project model.
- the attribute can be automagically populated upon project creation with updates to the project creation routes (janus, etna).
- it can be managed later on via editing the project record in timur.

2) A project setting saved in janus, similar to the 'Project Type' setting used to mark projects as team / resource / community. Should back-filled as false for current projects, yet give option for setting either way in project creation routes (janus, etna).  Downside: maybe small, but this method adds a requirement of magma to check project settings with janus. Often, janus will be pinged anyway for user-authorization purposes, so I'm not sure how big a downside this really is.
I think this option works well because:
- janus seems the 'ideal' place for holding knowledge of potential 'project personalities' (a.k.a. different flavors of between/across app treatment differences).
- the setting can be automagically populated upon project creation with updates to the project creation routes (janus, etna).
- it can be managed later on via the janus project settings UI.

**Comment by graft** [comment]
Nice, I had the same two ideas. The main drawbacks of each that I can see:
1. Editors can toggle the flag on and off, which seems unsafe.
2. If the flag is in Janus, Magma has to phone Janus to find out if it is on every time it handles an update, not the best.

The third possibility, unstated but maybe implicit so far:
3. Finally add a `projects` table to Magma.

**Comment by graft** [comment]
Fixed by #1235
