### ISSUE TITLE
creating new orphan records via /update returns "successful" but does (?)nothing

### ISSUE THREAD

**Issue by dtm2451** [mountetna/monoetna#431]
At least I think it does nothing.

Bushra and I were trying to link some sc_rna_seq data inn magma via magmaR earlier.  I only noticed at the end that the target records and parent records for those samples did not exist.  (So Bushra is going to work on the upstream sample/patient info before we try again.)

But this issue is about how the GET status returned was "successful" even though I don't believe anything was actually done?  Either nothing was done, or we created orphan records, but either way, perhaps a different status code should have been returned?

This was one of the three updates we'd tried:
```
{
   "project_name":"ipi",
   "revisions":{
      "sc_rna_seq":{
         "IPICRC136.N1.scrna.live":{
            "raw_counts_h5":{
               "original_filename":"raw_feature_bc_matrix.h5",
               "path":"metis://ipi/data/single_cell_GEX/processed/5prime_GEX/CRC/IPICRC136.N1.scrna.live/raw_feature_bc_matrix.h5"
            }
         }
      }
   }
}
```

**Comment by graft** [comment]
Your record is there, you can see it on Timur if you click the 'show disconnected records only' filter option. This is the intended behavior; the data inserts correctly, so you get a 200. The data can also be queried out successfully, with the correct query params. However, since it is attached to disconnected data, it won't show up in your typical query. If the data is attached to the graph again, then it should appear in a regular search once more.

**Comment by dtm2451** [comment]
roger roger!  Sorry that you probably told me this before!

I'm going to leave this open for now as a reminder that I should update `magmaR::updateValues()`'s record summarization to match.

**Comment by dtm2451** [comment]
Issue "solved" by adjusting the update-summaries to call records as "NEW (or orphan)" in #549.
