### ISSUE TITLE
magmaR bypassing validation

### ISSUE THREAD

**Issue by coleshaw** [mountetna/monoetna#542]
Raised in standup, not sure how this is happening?

**Comment by dtm2451** [comment]
Seems like the issue here is separate from the root cause of there being ".1"/".2" added initially, but is the reason those sample names were allowed: @coleshaw surfaced that validation is sample#sample_name validation is checked when data is added in the "down-the-tree" direction, BUT if the link is filled in during an update in the leaf-to-parent direction, validation is not run!
