### ISSUE TITLE
Query allows but fails to run "is present" on a model's identifier (to check for link existence)

### ISSUE THREAD

**Issue by dtm2451** [mountetna/monoetna#551]
Surfaced when I was looking to collect sc_seq records from HuMu which have linked CyTOF records.  @coleshaw 

## WITHOUT 'where' filter
![image](https://user-images.githubusercontent.com/38870347/134269032-d4b2b712-e5ae-4cd9-84ca-6a9c27ba2a93.png)

## WITH 'where' filter
![image](https://user-images.githubusercontent.com/38870347/134268986-ccebbd92-fd2a-4a32-99e9-e9afc2ecc995.png)

**Comment by coleshaw** [comment]
Hm, thanks! I wonder if it's a bug with the subqueries and the link. Will investigate... It is kind of interesting how the query was constructed though, because from the screenshots, there is no attribute for column 2 in the selector, but there is the right output in the query string preview. So that's also a bit odd. Any idea how you arrived at that state?
