### ISSUE TITLE
query#action logs show a truncated log line

### ISSUE THREAD

**Issue by graft** [mountetna/monoetna#669]
Magma log output includes the regular Etna controller logging, but the log for the query endpoint does not seem to show the complete input. E.g. this line: `calling query#action with params {:query=>"[\"::first\", \"::identifier\"]", :project_name=>"mvir1"}` which is evidently the final clause of a valid query, but not the entire thing. Perhaps a result of recent changes to log redacting?

**Comment by coleshaw** [comment]
Ah thanks, this is a good catch! I suspect the behavior changed because of [this line](https://github.com/mountetna/monoetna/blob/master/magma/lib/magma/query/question.rb#L52) when the `Magma::Question` is initialized and the passed-in `query_args` are shifted. Previously the route log recorded `@params[:query]` before stuff was shifted out, and now since the logging happens post-controller action, `@params[:query]` has been modified.

```
  class Question
    attr_reader :user
    def initialize(project_name, query_args, options = {})
      @model = Magma.instance.get_model(project_name, query_args.shift)
      @options = options
      @user = options[:user]
      @start_predicate = StartPredicate.new(self, @model, *query_args)
    end
```

I'll include a patch in PR #668 .
